// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/resolve/exception-triage-approval.yaml
// Flow: exception-triage-approval (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";
import { loginAs, USERS } from "../../../tests/browser/_helpers";

test.describe("exception-triage-approval", () => {
  test("happy path", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.goto("/exceptions/exc-026");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
    await expect(page.locator("button:has-text(\"Approve\")")).toBeVisible();
    await page.locator("button:has-text(\"Approve\")").click();
    await expect(page.locator("textarea[placeholder^=\"Add approval notes\"]")).toBeVisible();
    await expect(page.locator("textarea[placeholder^=\"Add approval notes\"]")).toBeFocused();
    await page.locator("button:has-text(\"Confirm Approval\")").click();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toContainText("Exception exc-026 approved");
  });

});
