// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/resolve/exception-triage-approval.yaml
// Flow: exception-triage-approval (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";

test.describe.fixme("exception-triage-approval", () => {
  // SKIP REASON: Codegen does not yet emit a loginAs() step before page.goto for authenticated entries. The middleware redirects to /login and every assertion fires against the login page DOM. Un-skip once flow-codegen.ts is taught to inject loginAs() (or the flow YAML schema declares an authAs role).
  test("happy path", async ({ page }) => {
    await page.goto("/exceptions/exc-026");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
    await expect(page.locator("button:has-text(\"Approve\")")).toBeVisible();
    await page.locator("button:has-text(\"Approve\")").click();
    await expect(page.locator("textarea[placeholder^=\"Add approval notes\"]")).toBeVisible();
    await expect(page.locator("textarea[placeholder^=\"Add approval notes\"]")).toBeFocused();
    await page.locator("button:has-text(\"Confirm Approval\")").click();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toContainText("Exception exc-026 approved");
  });

});
