// Scenario: BACK_ORDER record in FAILED terminal state. All HITL
// actions forbidden (terminal records reject disposition).
import type { BehaviourScenario } from "./_types";

export const BACK_ORDER__failed_terminal: BehaviourScenario = {
  id: "BACK_ORDER__failed_terminal",
  slo_category: "p95_blocker",
  customer_visible_urgency: "batch",
  intent: "BACK_ORDER",
  case: {
    case_id: "case-bo-777",
    tenant_id: "acme-corp",
    source: "automated_order",
    source_channel: "edi_x12_850",
    customer_po_number: "PO-2026-7777",
    opened_at: "2026-05-09T14:00:00Z",
    closed_at: "2026-05-10T02:00:00Z",
    updated_at: "2026-05-10T02:00:00Z",
    status: "FAILED",
    tier: 2,
    child_intents: ["BACK_ORDER"],
  },
  records: [
    {
      id: "exc-bo-777",
      tenant_id: "acme-corp",
      order_id: "PO-2026-7777",
      event_type: "EDI_850_BACKORDER",
      intent: "BACK_ORDER",
      lifecycle_state: "FAILED",
      shadow_verdict: "RED",
      selected_recipe: "BackOrderResolutionRecipe.py",
      final_status: "FAIL_TO_HUMAN",
      created_at: "2026-05-09T14:00:00Z",
      updated_at: "2026-05-10T02:00:00Z",
      account_id: "acct-walmart-na",
      account_name: "Walmart North America",
      parent_case_id: "case-bo-777",
    },
  ],
  detail: {
    id: "exc-bo-777",
    tenant_id: "acme-corp",
    order_id: "PO-2026-7777",
    event_type: "EDI_850_BACKORDER",
    intent: "BACK_ORDER",
    lifecycle_state: "FAILED",
    shadow_verdict: "RED",
    selected_recipe: "BackOrderResolutionRecipe.py",
    final_status: "FAIL_TO_HUMAN",
    created_at: "2026-05-09T14:00:00Z",
    updated_at: "2026-05-10T02:00:00Z",
    account_id: "acct-walmart-na",
    account_name: "Walmart North America",
    parent_case_id: "case-bo-777",
    resolution_data: {},
  },
  allowed_actions: {
    approve: { allowed: false },
    reject:  { allowed: false },
    override: {
      allowed: false,
      reason_tags: [
        "ALTERNATE_WAREHOUSE_APPROVED",
        "SUBSTITUTE_SKU_APPROVED",
        "CUSTOMER_ACCEPTS_DELAY",
        "PARTIAL_FULFILMENT_ACCEPTED",
        "CANCELLATION_ACCEPTED",
        "OTHER",
      ],
    },
    escalate: { allowed: false },
    reanalyze: { allowed: false },
    cosign: { allowed: false },
  },
  expected_ws_events: [],
  tier: 2,
};
