// Scenario: MANUAL_ORDER_INTAKE record at LOW_CONFIDENCE; approve
// allowed, no cosign required. Touches the quick-Approve happy path
// (the path S1 fixes for casing).
import type { BehaviourScenario } from "./_types";

export const MANUAL_ORDER_INTAKE__low_confidence_clarify_buyer: BehaviourScenario = {
  id: "MANUAL_ORDER_INTAKE__low_confidence_clarify_buyer",
  slo_category: "p99_blocker",
  customer_visible_urgency: "same_business_day",
  intent: "MANUAL_ORDER_INTAKE",
  case: {
    case_id: "case-moi-042",
    tenant_id: "acme-corp",
    origin: "CUSTOMER",
    source_channel: "email",
    supergroup_code: "SG_NEW_ORDER",
    source_email_id: "msg-2026-05-10-7782",
    opened_at: "2026-05-10T08:00:00Z",
    updated_at: "2026-05-10T08:15:00Z",
    status: "OPEN_AWAITING_HUMAN",
    sla_deadline: "2026-05-10T20:00:00Z",
    will_miss_rdd: false,
    tier: 2,
    child_intents: ["MANUAL_ORDER_INTAKE"],
    // ADR-041 P3e §3.1 — CaseSummary projection (mock-null).
    customer_name: null,
    top_line_sku_code: null,
    top_line_sku_title: null,
    problem_one_liner: null,
    intent: "MANUAL_ORDER_INTAKE",
    dollar_impact: null,
    audit_verdict_color: null,
    attention_state: "NEEDS_HUMAN",
  },
  records: [
    {
      id: "exc-moi-042",
      tenant_id: "acme-corp",
      order_id: "EML-PO-2026-0042",
      event_type: "EMAIL_ORDER_ENTRY_REQUEST",
      intent: "MANUAL_ORDER_INTAKE",
      lifecycle_state: "PENDING_REVIEW",
      shadow_verdict: "YELLOW",
      selected_recipe: "EmailOrderEntryRecipe.py",
      final_status: "MANUAL_REVIEW_REQUIRED",
      created_at: "2026-05-10T08:00:00Z",
      updated_at: "2026-05-10T08:10:00Z",
      account_id: "acct-southeast-distrib",
      account_name: "Southeast Beverage Distributors",
      parent_case_id: "case-moi-042",
    },
  ],
  detail: {
    id: "exc-moi-042",
    tenant_id: "acme-corp",
    order_id: "EML-PO-2026-0042",
    event_type: "EMAIL_ORDER_ENTRY_REQUEST",
    intent: "MANUAL_ORDER_INTAKE",
    lifecycle_state: "PENDING_REVIEW",
    shadow_verdict: "YELLOW",
    selected_recipe: "EmailOrderEntryRecipe.py",
    final_status: "MANUAL_REVIEW_REQUIRED",
    created_at: "2026-05-10T08:00:00Z",
    updated_at: "2026-05-10T08:10:00Z",
    account_id: "acct-southeast-distrib",
    account_name: "Southeast Beverage Distributors",
    parent_case_id: "case-moi-042",
    resolution_data: {},
  },
  email_source: {
    from_address: "buyer@southeastbev.example",
    received_at: "2026-05-10T07:55:00Z",
    subject: "Order for next week — pallet quantities",
    body_hash: "sha256:5a4bd6f1c0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0",
    attachment_manifest: [],
    body_excerpt: "Please ship the usual cases of sports drink…",
    source_email_id: "msg-2026-05-10-7782",
  },
  allowed_actions: {
    approve: { allowed: true, reason_tag: "OTHER" },
    reject:  { allowed: true, reason_tag: "OTHER" },
    override: {
      allowed: true,
      reason_tags: [
        "EXTRACTION_LOW_CONFIDENCE",
        "FIELD_MISSING_BUYER_CLARIFIED",
        "FIELD_MISSING_BUYER_UNREACHABLE",
        "UNSUPPORTED_FORMAT",
        "MULTI_PO_SPLIT",
        "OTHER",
      ],
    },
    escalate: { allowed: true },
    reanalyze: { allowed: true },
    cosign: { allowed: false },
  },
  expected_ws_events: [],
  tool_call_sequence: ["extract_attachment", "score_intake_confidence", "resolve_buyer_identity"],
  tier: 2,
};
