// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/triage/case-to-exception-detail-roundtrip.yaml
// Flow: case-to-exception-detail-roundtrip (regression)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";
import { loginAs, USERS } from "../../../tests/browser/_helpers";

test.describe("case-to-exception-detail-roundtrip", () => {
  test("happy path", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.goto("/cases");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
    await page.goto("/cases/case-001");
    await expect(page).toHaveURL("/cases/case-001");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
    await page.goto("/exceptions/exc-026");
    await expect(page).toHaveURL("/exceptions/exc-026");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
    await page.goBack();
    await expect(page).toHaveURL("/cases/case-001");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
    await page.goBack();
    await expect(page).toHaveURL("/cases");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
  });

});
