// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/triage/email-order-entry-from-inbox.yaml
// Flow: email-order-entry-from-inbox (regression)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";
import { loginAs, USERS } from "../../../tests/browser/_helpers";

test.describe("email-order-entry-from-inbox", { tag: ["@flow-email-order-entry-from-inbox", "@arc-task-completion", "@kind-regression", "@journey-J1"] }, () => {
  test("happy path", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.goto("/exceptions/exc-026?from=inbox");
    await expect(page.locator("text=\"Back to Inbox\"")).toBeVisible();
    await expect(page.locator("h1, [role=\"heading\"][aria-level=\"1\"]")).toBeFocused();
    await page.locator("text=\"Back to Inbox\"").click();
    await expect(page).toHaveURL("/cases?source=manual_order");
  });

});
