// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/triage/email-order-entry-from-inbox.yaml
// Flow: email-order-entry-from-inbox (regression)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";

test.describe.fixme("email-order-entry-from-inbox", () => {
  // SKIP REASON: V1 regression flow. Issue #133 retired /inbox as a master- detail surface; the email-order-entry row + jump button no longer live there. Re-target to /cases?source=manual_order (the post-#133 home of manual-order cases) and update the row selectors to match CaseListPane's DOM. Plus codegen lacks loginAs plumbing.
  test("happy path", async ({ page }) => {
    await page.goto("/inbox");
    await expect(page.locator("[data-testid=\"inbox-row\"]")).toBeVisible();
    await page.locator("[role=\"button\"][aria-label*=\"PO 4501234567\"]").click();
    await expect(page.locator("text=\"Open in Exception Queue\"")).toBeVisible();
    await page.locator("text=\"Open in Exception Queue\"").click();
    await expect(page).toHaveURL("/exceptions/exc-026?from=inbox");
    await expect(page.locator("text=\"Back to Inbox\"")).toBeVisible();
    await expect(page.locator("h1, [role=\"heading\"][aria-level=\"1\"]")).toBeFocused();
    await page.locator("text=\"Back to Inbox\"").click();
    await expect(page).toHaveURL("/inbox");
  });

});
