// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/triage/inbox-load.yaml
// Flow: inbox-load (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";
import { loginAs, USERS } from "../../../tests/browser/_helpers";

test.describe("inbox-load", { tag: ["@flow-inbox-load", "@arc-orientation", "@kind-golden", "@journey-J1", "@journey-J2"] }, () => {
  test("happy path", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.goto("/cases?source=manual_order");
    await expect(page.locator("button[aria-label^=\"Open case \"]")).toBeVisible();
  });

  test("state: loading", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    let resolveRoute: () => void = () => {};
    const routeReady = new Promise<void>((r) => { resolveRoute = r; });
    await page.route("/api/v1/cases**", async (route) => {
      await routeReady;
      await route.continue();
    });
    const navigation = page.goto("/cases?source=manual_order");
    // PHASE 2 — assert-during: skeleton must be visible while load is pending.
    await expect(page.locator("role=status[name=\"Loading cases…\"]")).toBeVisible();
    resolveRoute();
    await navigation;
  });

  test("state: empty", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.route("/api/v1/cases**", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: "{\"items\":[],\"total\":0,\"cursor\":null,\"has_more\":false}",
      });
    });
    await page.goto("/cases?source=manual_order");
    await expect(page.getByText("No cases match the current filters.")).toBeVisible();
  });

});
