// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/triage/inbox-load.yaml
// Flow: inbox-load (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";

test.describe.fixme("inbox-load", () => {
  // SKIP REASON: Entry path was migrated post-rebase to the correct surface (Issue #133), but the selectors ([data-testid="inbox-row"], [data-testid="inbox-skeleton"], [data-testid="inbox-empty- cta"], [data-testid="inbox-error-retry"]) still target the retired rich-inbox DOM. Re-author the assertions against CaseListPane's actual testids. Plus codegen lacks loginAs plumbing.
  test("happy path", async ({ page }) => {
    await page.goto("/cases?source=manual_order");
    await expect(page.locator("[data-testid=\"inbox-row\"]")).toBeVisible();
  });

  test("state: loading", async ({ page }) => {
    let resolveRoute: () => void = () => {};
    const routeReady = new Promise<void>((r) => { resolveRoute = r; });
    await page.route("/api/v1/exceptions", async (route) => {
      await routeReady;
      await route.continue();
    });
    const navigation = page.goto("/cases?source=manual_order");
    // PHASE 2 — assert-during: skeleton must be visible while load is pending.
    await expect(page.locator("[data-testid=\"inbox-skeleton\"]")).toBeVisible();
    resolveRoute();
    await navigation;
  });

  test("state: empty", async ({ page }) => {
    await page.route("/api/v1/exceptions", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: "[]",
      });
    });
    await page.goto("/cases?source=manual_order");
    await expect(page.locator("[data-testid=\"inbox-empty-cta\"]")).toBeVisible();
    await expect(page.getByText("You're caught up")).toBeVisible();
  });

  test("state: error", async ({ page }) => {
    await page.route("/api/v1/exceptions", async (route) => {
      await route.fulfill({
        status: 500,
        contentType: "application/json",
        body: "null",
      });
    });
    await page.goto("/cases?source=manual_order");
    await expect(page.locator("[data-testid=\"inbox-error-retry\"]")).toBeVisible();
  });

});
