// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/triage/inbox-item-click-behavior-catalog.yaml
// Flow: inbox-item-click-behavior-catalog (regression)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";

test.describe.fixme("inbox-item-click-behavior-catalog", () => {
  // SKIP REASON: V3 regression flow — the catalogue of click semantics across inbox item types. Issue #133 retired the rich /inbox surface; the 6 seed INBOX rows no longer render with these aria-labels. Rewrite against /cases?source=manual_order or whatever canonical surface still exposes the per-type semantics. Plus codegen lacks loginAs plumbing.
  test("happy path", async ({ page }) => {
    await page.goto("/inbox");
    await expect(page.locator("[data-testid=\"inbox-row\"]")).toBeVisible();
    await page.locator("[role=\"button\"][aria-label*=\"Change request\"]").click();
    await expect(page).toHaveURL("/inbox");
    await expect(page.locator("text=\"Change request — SO 4500023421\"")).toBeVisible();
    await page.locator("[role=\"button\"][aria-label*=\"Where is my shipment\"]").click();
    await expect(page).toHaveURL("/inbox");
    await page.locator("[role=\"button\"][aria-label*=\"Beverages Dept\"]").click();
    await expect(page).toHaveURL("/inbox");
    await page.locator("[role=\"button\"][aria-label*=\"PO 4501234567\"]").click();
    await expect(page).toHaveURL("/inbox");
    await expect(page.locator("text=\"Open in Exception Queue\"")).toBeVisible();
    await page.locator("[role=\"button\"][aria-label*=\"critical delivery failure\"]").click();
    await expect(page).toHaveURL("/inbox");
    await page.locator("[role=\"button\"][aria-label*=\"Invoice question\"]").click();
    await expect(page).toHaveURL("/inbox");
  });

});
