// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/__tests__/fixtures/sample-flow.yaml
// Flow: sample-flow (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";
import { loginAs, USERS } from "../../../tests/browser/_helpers";

test.describe("sample-flow", () => {
  test("happy path", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.goto("/inbox");
    await expect(page.locator("[data-testid=\"inbox-row\"]")).toBeVisible();
    await page.locator("[data-testid=\"inbox-row-3\"]").click();
    await expect(page.locator("[data-testid=\"exception-detail-heading\"]")).toBeFocused();
    await expect(page).toHaveURL("/exceptions/exc-001?from=inbox");
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toContainText("Exception loaded");
  });

  test("state: loading", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    let resolveRoute: () => void = () => {};
    const routeReady = new Promise<void>((r) => { resolveRoute = r; });
    await page.route("/api/v1/exceptions", async (route) => {
      await routeReady;
      await route.continue();
    });
    const navigation = page.goto("/inbox");
    // PHASE 2 — assert-during: skeleton must be visible while load is pending.
    await expect(page.locator("[data-testid=\"inbox-skeleton\"]")).toBeVisible();
    resolveRoute();
    await navigation;
  });

  test("state: empty", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.route("/api/v1/exceptions", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: "[]",
      });
    });
    await page.goto("/inbox");
    await expect(page.locator("[data-testid=\"inbox-empty-cta\"]")).toBeVisible();
    await expect(page.getByText("You're caught up")).toBeVisible();
  });

  test("state: error", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.route("/api/v1/exceptions", async (route) => {
      await route.fulfill({
        status: 500,
        contentType: "application/json",
        body: "null",
      });
    });
    await page.goto("/inbox");
    await expect(page.locator("[data-testid=\"inbox-error-retry\"]")).toBeVisible();
  });

});
