// Flow codegen — translates a parsed flow YAML into a Playwright
// .spec.ts file (W7 + A1).
//
// Decision A1 (docs/test-strategy/e2e-flow-plan.md):
//   "Generated specs are real Playwright tests with normal stack
//    traces, normal IDE jump-to-definition, normal Playwright UI
//    mode debugging. Trace failures point at generated .spec.ts
//    line numbers humans can read."
//
// This module is the load-bearing translator. T1 covers it with a
// golden-output unit test (e2e/__tests__/flow-codegen.test.ts) so
// any drift in the generated text fails CI loudly rather than
// silently degrading every flow's coverage.
//
// Implementation principles (eng-review locked):
//   - Deterministic output: identical input -> identical bytes.
//     No timestamps, no Set ordering, no random IDs.
//   - Strict validation upfront via zod (e2e/flow-schema.ts).
//   - One Playwright test() block per state in the matrix, plus
//     one for the happy-path steps. Each test is self-contained
//     so a failure points at exactly one state.
//   - Mock setup uses Playwright's page.route() (decision A3).
//   - Loading state uses the deferred-promise pattern (decision P1).

import type { Flow, StateFixture, StateKey, Step } from "./flow-schema";
import { parseFlow } from "./flow-schema";

export interface CodegenInput {
  // The raw object parsed from YAML (e.g. via `yaml.parse(text)`).
  rawFlow: unknown;
  // Flow file path relative to the repo root, used in the header
  // for traceability. Pass the YAML path so editor jump-to-source
  // points back at the human-edited file.
  sourcePath: string;
}

export interface CodegenOutput {
  // The generated TypeScript spec text. Write to disk verbatim.
  spec: string;
  // The Flow object after schema validation. Surfaced so callers
  // (the build script) can also use it for indexing / linting.
  flow: Flow;
}

export function generateSpec(input: CodegenInput): CodegenOutput {
  const flow = parseFlow(input.rawFlow);
  const lines: string[] = [];

  // Header — DO NOT EDIT marker, source path, schema reference.
  lines.push(
    "// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.",
    `// Source: ${input.sourcePath}`,
    `// Flow: ${flow.name} (${flow.kind})`,
    "// Edits are clobbered by `bun run flows:gen`. Update the YAML.",
    "",
    'import { expect, test } from "@playwright/test";',
    "",
  );

  // describe wrapper. If the flow opts into `skip:`, emit
  // `test.describe.fixme(...)` so Playwright reports the skip
  // with the citation but does not fail. Used while a flow's
  // selectors / login plumbing are still being validated.
  const describeFn = flow.skip
    ? "test.describe.fixme"
    : "test.describe";
  const skipBanner = flow.skip
    ? [`  // SKIP REASON: ${flow.skip.reason}`]
    : [];

  // Happy-path test — runs the steps with no state mocks.
  lines.push(
    `${describeFn}(${q(flow.name)}, () => {`,
    ...skipBanner,
    `  test(${q("happy path")}, async ({ page }) => {`,
    `    await page.goto(${q(flow.entry)});`,
  );
  for (const step of flow.steps) {
    for (const out of emitStep(step)) {
      lines.push(`    ${out}`);
    }
  }
  lines.push("  });", "");

  // One test() per state in the matrix.
  if (flow.states && flow.states.length > 0) {
    const fixtures = flow.state_fixtures ?? {};
    for (const stateKey of flow.states) {
      const fx = fixtures[stateKey];
      if (!fx) continue; // schema enforces presence; defensive only.
      lines.push(...emitStateTest(flow, stateKey, fx));
    }
  }

  lines.push("});", "");
  return { spec: lines.join("\n"), flow };
}

function emitStateTest(
  flow: Flow,
  stateKey: StateKey,
  fx: StateFixture,
): string[] {
  const out: string[] = [];
  out.push(`  test(${q(`state: ${stateKey}`)}, async ({ page }) => {`);
  if (stateKey === "loading" && typeof fx.delay_ms === "number") {
    // P1: deferred-promise + assert-during pattern.
    out.push(
      "    let resolveRoute: () => void = () => {};",
      "    const routeReady = new Promise<void>((r) => { resolveRoute = r; });",
      `    await page.route(${q(fx.route)}, async (route) => {`,
      "      await routeReady;",
      "      await route.continue();",
      "    });",
      `    const navigation = page.goto(${q(flow.entry)});`,
      "    // PHASE 2 — assert-during: skeleton must be visible while load is pending.",
    );
    if (fx.assert_visible) {
      out.push(
        `    await expect(page.locator(${q(fx.assert_visible)})).toBeVisible();`,
      );
    }
    out.push("    resolveRoute();", "    await navigation;");
  } else {
    // Standard mock: respond with the configured body / status / fixture.
    out.push(
      `    await page.route(${q(fx.route)}, async (route) => {`,
      ...emitRouteFulfill(fx).map((s) => `      ${s}`),
      "    });",
      `    await page.goto(${q(flow.entry)});`,
    );
  }
  if (fx.assert_visible && stateKey !== "loading") {
    out.push(
      `    await expect(page.locator(${q(fx.assert_visible)})).toBeVisible();`,
    );
  }
  if (fx.assert_visible_count) {
    out.push(
      `    await expect(page.locator(${q(fx.assert_visible_count)}).first()).toBeVisible();`,
    );
  }
  if (fx.assert_text_contains && fx.assert_text_contains.length > 0) {
    for (const text of fx.assert_text_contains) {
      out.push(
        `    await expect(page.getByText(${q(text)})).toBeVisible();`,
      );
    }
  }
  out.push("  });", "");
  return out;
}

function emitRouteFulfill(fx: StateFixture): string[] {
  if (fx.fixture) {
    // Reference a named fixture file; the runtime loader is a
    // V1.1 concern. For now we throw at runtime so the missing
    // wiring is loud, not silent.
    return [
      `throw new Error("named fixture loader not yet wired: " + ${q(fx.fixture)});`,
    ];
  }
  const status = fx.status ?? 200;
  const body = JSON.stringify(fx.body ?? null);
  return [
    "await route.fulfill({",
    `  status: ${status},`,
    `  contentType: "application/json",`,
    `  body: ${q(body)},`,
    "});",
  ];
}

function emitStep(step: Step): string[] {
  switch (step.action) {
    case "click":
      return [
        `await page.locator(${q(step.selector!)}).click();`,
      ];
    case "press":
      return [`await page.keyboard.press(${q(step.key!)});`];
    case "fill":
      return [
        `await page.locator(${q(step.selector!)}).fill(${q(step.value ?? "")});`,
      ];
    case "navigate":
      return [`await page.goto(${q(step.url!)});`];
    case "back":
      // Browser back: bfcache when available, otherwise re-mount.
      // V2 asserts chrome survives this transition.
      return ["await page.goBack();"];
    case "forward":
      return ["await page.goForward();"];
    case "assert_visible":
      return [
        `await expect(page.locator(${q(step.selector!)})).toBeVisible();`,
      ];
    case "assert_url_equals":
      // D4: prefer assert_url_equals over regex when the ID is known.
      return [`await expect(page).toHaveURL(${q(step.url!)});`];
    case "assert_url_matches":
      return [`await expect(page).toHaveURL(${pattern(step.pattern!)});`];
    case "assert_focus_on":
      return [
        `await expect(page.locator(${q(step.selector!)})).toBeFocused();`,
      ];
    case "assert_announcement_text":
      // Q1: single canonical StatusAnnouncer testid.
      return [
        `await expect(page.locator(${q('[data-testid="status-announcer"]')})).toContainText(${q(step.text ?? "")});`,
      ];
  }
}

// JSON-encoded string literal — handles backslashes, quotes,
// newlines, and unicode without ad-hoc escaping. Output is always
// double-quoted so the generated spec parses uniformly.
function q(s: string): string {
  return JSON.stringify(s);
}

// Wrap a regex pattern as a RegExp literal in the generated spec.
function pattern(p: string): string {
  return `new RegExp(${q(p)})`;
}
