// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/signout/signout-from-each-role.yaml
// Flow: signout-from-each-role (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";

test.describe("signout-from-each-role", () => {
  test("happy path", async ({ page }) => {
    await page.goto("/inbox");
    await expect(page.locator("button[aria-label=\"User menu\"]")).toBeVisible();
    await page.locator("button[aria-label=\"User menu\"]").click();
    await expect(page.locator("[role=\"menuitem\"]:has-text(\"Sign out\")")).toBeVisible();
    await page.locator("[role=\"menuitem\"]:has-text(\"Sign out\")").click();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toContainText("Signing out");
    await expect(page).toHaveURL("/login");
    await expect(page.locator("input[placeholder=\"jane@acme.com\"]")).toBeFocused();
  });

});
