/**
 * UI route conformance — every `/api/...` route the UI client calls
 * must exist in the sibling asoe2 OpenAPI document. Catches:
 *
 *   * UI calling a route the backend never exposed (typo, copy-paste).
 *   * Backend retiring a route the UI still calls.
 *
 * The route snapshot at tests/contract/snapshots/ui_route_surface.json
 * is regenerated by `npm run sync:ui-routes`; this test fails the
 * build when:
 *   * The committed snapshot doesn't match what the extractor would
 *     emit on the current src/lib/api.ts (drift in either direction).
 *   * Any route in the snapshot is missing from the OpenAPI paths.
 *
 * Method-level conformance is a follow-on; path-level is the
 * high-value check today. (Reviewer panel: Boris/SRE/Compliance
 * amendment requires that the UI side mirror asoe2's
 * tests/contract/test_stub_schema_conformance.py — this is the
 * path-surface leg; payload-schema validation follows in S8.)
 */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, it, expect } from "vitest";

const REPO_ROOT = path.resolve(__dirname, "../..");
const SNAPSHOT_PATH = path.resolve(REPO_ROOT, "tests/contract/snapshots/ui_route_surface.json");
const OPENAPI_PATH = path.resolve(REPO_ROOT, "..", "asoe2", "openapi", "asoe2.openapi.json");
const API_TS = path.resolve(REPO_ROOT, "src/lib/api.ts");

describe("UI route conformance", () => {
  if (!existsSync(OPENAPI_PATH)) {
    it.skip("sibling asoe2 OpenAPI missing — skipping conformance check", () => {});
    return;
  }

  const snapshot = JSON.parse(readFileSync(SNAPSHOT_PATH, "utf-8")) as {
    routes: { path: string; raw: string }[];
  };
  const openapi = JSON.parse(readFileSync(OPENAPI_PATH, "utf-8")) as {
    paths: Record<string, unknown>;
  };
  const openapiPaths = new Set(Object.keys(openapi.paths ?? {}));

  it("captures every http<T>() callsite in src/lib/api.ts", () => {
    // Sanity floor: if the extractor regex regresses, this test
    // notices because the snapshot drops below the floor we expect.
    // S1 + S3 produced 12 routes; adjust this floor when adding
    // routes intentionally.
    expect(snapshot.routes.length).toBeGreaterThanOrEqual(10);
  });

  it("every UI-side /api/v1/... path exists in asoe2 OpenAPI", () => {
    const missing = snapshot.routes
      .filter((r) => r.path.startsWith("/api/v1/"))
      .filter((r) => !openapiPaths.has(r.path));
    expect(
      missing,
      `UI calls routes the OpenAPI does not expose: ${JSON.stringify(missing.map((r) => r.path))}`,
    ).toEqual([]);
  });

  it("auth routes (/api/auth/*) are documented as UI-only", () => {
    // /api/auth/login lives in NextAuth-land, not asoe2's OpenAPI.
    // We assert the snapshot only lists known-permitted auth routes
    // so a typo doesn't slip through under "auth router" cover.
    const PERMITTED_AUTH = new Set(["/api/auth/login"]);
    const unknown = snapshot.routes
      .filter((r) => r.path.startsWith("/api/auth/"))
      .filter((r) => !PERMITTED_AUTH.has(r.path));
    expect(unknown).toEqual([]);
  });

  it("snapshot is byte-identical to what the extractor emits today", () => {
    // Cheap drift guard: re-derive the route list using the same
    // regex the extractor uses, compare. If this fails, run
    // `npm run sync:ui-routes` and commit.
    const src = readFileSync(API_TS, "utf-8");
    const re = /\bhttp\s*<\s*[A-Za-z_][A-Za-z0-9_<>,\s]*\s*>\s*\(\s*(["`])((?:\\.|(?!\1).)*)\1/g;
    const observed = new Set<string>();
    let m: RegExpExecArray | null;
    while ((m = re.exec(src)) !== null) {
      const raw = m[2];
      if (raw.startsWith("/api/")) observed.add(raw);
    }
    const snapshotRaws = new Set(snapshot.routes.map((r) => r.raw));
    const inSrcOnly = [...observed].filter((r) => !snapshotRaws.has(r));
    const inSnapshotOnly = [...snapshotRaws].filter((r) => !observed.has(r));
    expect(
      { inSrcOnly, inSnapshotOnly },
      "snapshot drift — run `npm run sync:ui-routes`",
    ).toEqual({ inSrcOnly: [], inSnapshotOnly: [] });
  });
});
