/**
 * Contract parity: the curated reason-tag snapshot must match the
 * sibling asoe2 source-of-truth byte-for-byte. The snapshot is
 * regenerated by `npm run sync:reason-tags`; this test fails the
 * build whenever the snapshot drifts from `../asoe2/constraints/specs.py`.
 *
 * Skipped (with a console warning) when the sibling checkout is not
 * present — the parity test is only meaningful in environments that
 * carry both repos. CI provisions both; developer machines typically do.
 */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, it, expect } from "vitest";

const REPO_ROOT = path.resolve(__dirname, "../..");
const SIBLING_SPECS = path.resolve(REPO_ROOT, "..", "asoe2", "constraints", "specs.py");
const SNAPSHOT_PATH = path.resolve(REPO_ROOT, "tests/contract/snapshots/curated_reason_tags.json");

describe("curated reason-tag snapshot parity with asoe2", () => {
  if (!existsSync(SIBLING_SPECS)) {
    it.skip("sibling asoe2 checkout missing — skipping parity check", () => {});
    return;
  }

  it("committed snapshot matches what the sync script would emit", () => {
    // Re-run the sync script with a redirected output path (we don't
    // mutate the working tree). Diff the resulting JSON against the
    // committed snapshot.
    const committed = JSON.parse(readFileSync(SNAPSHOT_PATH, "utf-8"));

    // Pull the fields the script extracts ourselves so the test is
    // independent of the script's output-directory side-effects.
    const specs = readFileSync(SIBLING_SPECS, "utf-8");

    // Re-parse `_CURATED_INTENT_REASON_TAGS` using the same regex
    // shape the sync script uses.
    const tuples = new Map<string, string[]>();
    const tupleRe = /^(_[A-Z][A-Z0-9_]*_REASON_TAGS):\s*tuple\[str,\s*\.\.\.\]\s*=\s*\(([\s\S]*?)\n\)/gm;
    const stringRe = /"([^"\\]+)"/g;
    for (const m of specs.matchAll(tupleRe)) {
      tuples.set(m[1], [...m[2].matchAll(stringRe)].map((x) => x[1]));
    }
    const dictRe = /_CURATED_INTENT_REASON_TAGS:\s*dict\[str,\s*tuple\[str,\s*\.\.\.\]\]\s*=\s*\{([\s\S]*?)^\}/m;
    const dictMatch = specs.match(dictRe);
    expect(dictMatch, "asoe2 _CURATED_INTENT_REASON_TAGS dict not found").not.toBeNull();
    const dictEntryRe = /"([A-Z][A-Z0-9_]+)"\s*:\s*(_[A-Z][A-Z0-9_]*_REASON_TAGS)/g;
    const curated: Record<string, string[]> = {};
    for (const m of dictMatch![1].matchAll(dictEntryRe)) {
      const vocab = tuples.get(m[2]);
      expect(vocab, `tuple ${m[2]} referenced by ${m[1]} not parsed`).toBeDefined();
      curated[m[1]] = vocab!;
    }
    const literalRe = /^AllowedOverrideReasonTag\s*=\s*Literal\[([\s\S]*?)^\]/m;
    const literalMatch = specs.match(literalRe);
    expect(literalMatch, "asoe2 AllowedOverrideReasonTag Literal not found").not.toBeNull();
    const allTags = [...literalMatch![1].matchAll(stringRe)].map((x) => x[1]);

    // Compare each field individually so failures point at the drift.
    expect(committed.allowed_override_reason_tags).toEqual(allTags);
    expect(committed.allowed_override_reason_tags_by_intent).toEqual(
      Object.fromEntries(Object.keys(curated).sort().map((k) => [k, curated[k]])),
    );
  });

  it("MOCK_HEALTH.allowed_override_reason_tags_by_intent matches the snapshot", async () => {
    const snapshot = JSON.parse(readFileSync(SNAPSHOT_PATH, "utf-8"));
    const { MOCK_HEALTH } = await import("../fixtures");
    expect(MOCK_HEALTH.allowed_override_reason_tags_by_intent).toEqual(
      snapshot.allowed_override_reason_tags_by_intent,
    );
    expect(MOCK_HEALTH.allowed_override_reason_tags).toEqual(
      snapshot.allowed_override_reason_tags,
    );
  });

  it("scenario library reason_tag values are members of the curated vocab", async () => {
    const snapshot = JSON.parse(readFileSync(SNAPSHOT_PATH, "utf-8"));
    const { SCENARIOS } = await import("../scenarios");
    for (const s of SCENARIOS) {
      const vocab = snapshot.allowed_override_reason_tags_by_intent[s.intent];
      if (!vocab) continue;  // intent not curated yet — falls back to global
      const tags = s.allowed_actions.override.reason_tags ?? [];
      for (const t of tags) {
        expect(
          vocab,
          `scenario ${s.id} override reason_tag "${t}" not in curated vocab for ${s.intent}`,
        ).toContain(t);
      }
    }
  });
});
