/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa Verify */
        post: operations["mfa_verify_api_auth_mfa_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sso/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sso Callback */
        get: operations["sso_callback_api_auth_sso_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sso/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sso Init */
        post: operations["sso_init_api_auth_sso_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Accounts
         * @description Return all accounts for the tenant. Scoped users see only their assigned accounts.
         */
        get: operations["get_accounts_api_v1_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exceptions */
        get: operations["list_exceptions_api_v1_exceptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve */
        post: operations["resolve_api_v1_exceptions_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/resolve/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Async */
        post: operations["resolve_async_api_v1_exceptions_resolve_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/resolve/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Explain */
        post: operations["resolve_explain_api_v1_exceptions_resolve_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_v1_exceptions_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exception */
        get: operations["get_exception_api_v1_exceptions__exception_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/admin-release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Release Exception
         * @description RED-tier HITL: admin releases a RED-blocked exception.
         *
         *     Transitions BLOCKED → PENDING_ADMIN_REVIEW.
         *     The admin must then approve, override, or reject the exception.
         *     The original RED verdict is preserved in the TraceRecord.
         *     risk_acknowledgment must be True (explicit risk acceptance).
         */
        post: operations["admin_release_exception_api_v1_exceptions__exception_id__admin_release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_v1_exceptions__exception_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Exception */
        post: operations["approve_exception_api_v1_exceptions__exception_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Challenge Exception
         * @description GREEN-tier HITL: challenge a resolved exception for review.
         *
         *     Transitions RESOLVED → ESCALATED for investigation.
         *     Does NOT undo executed actions (gateway effects already applied).
         */
        post: operations["challenge_exception_api_v1_exceptions__exception_id__challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Escalate Exception
         * @description Escalate an exception into ESCALATED lifecycle (routing only).
         *
         *     Decoupled from Override: this endpoint changes routing without
         *     asserting a resolution action. Eligible lifecycles are
         *     ESCALATE_ELIGIBLE_STATES (PENDING_REVIEW, FAILED, BLOCKED). Already
         *     ESCALATED (no-op) and RESOLVED (use Challenge) return 409.
         *
         *     Supports the optional Idempotency-Key header (same semantics as
         *     /override).
         */
        post: operations["escalate_exception_api_v1_exceptions__exception_id__escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/line-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Line Items */
        get: operations["get_line_items_api_v1_exceptions__exception_id__line_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Override Exception
         * @description Override the agent's recommended action (Option A, Phase 1).
         *
         *     Privileged users (manager+) may Override across GREEN (RESOLVED),
         *     YELLOW (PENDING_REVIEW/ESCALATED), and RED (BLOCKED) verdicts.
         *     Analysts cannot Override (they use Approve/Reject on YELLOW).
         *
         *     The shadow_verdict must be one of GREEN/YELLOW/RED — FAILED-lifecycle
         *     exceptions (where no agent decision exists to override) are rejected
         *     with 409 INVALID_VERDICT.
         *
         *     The auditor identity is always ``user.sub`` (JWT); clients must not
         *     pass ``resolved_by``. Notes are mandatory (SOX audit requirement).
         *
         *     Supports an optional ``Idempotency-Key`` header. Repeat calls within
         *     24h return the cached response; conflicting bodies with the same key
         *     return 409 IDEMPOTENCY_CONFLICT.
         */
        patch: operations["override_exception_api_v1_exceptions__exception_id__override_patch"];
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/override/cosign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cosign Override
         * @description Second-reviewer decision on a pending high-value override.
         *
         *     Gating:
         *       - Lifecycle must be PENDING_COSIGN.
         *       - Caller must not be the pending_override.initiator (SoD).
         *       - Idempotency-Key supported identically to /override.
         *
         *     Outcome:
         *       - approve=True  → apply the pending override (lifecycle → RESOLVED,
         *                         resolved_by = initiator, cosigned_by = caller,
         *                         EXCEPTION_OVERRIDE_COSIGNED audit event).
         *       - approve=False → restore the prior lifecycle_state (stashed on the
         *                         pending_override), clear pending_override,
         *                         EXCEPTION_OVERRIDE_REJECTED audit event.
         */
        post: operations["cosign_override_api_v1_exceptions__exception_id__override_cosign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/reanalyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reanalyze Exception
         * @description Replay an exception through the full graph with a fresh Compliance
         *     Shadow decision.
         *
         *     Governance (mirrors CLAUDE.md §4):
         *     - Re-run flows through the same run_graph() pipeline — Compliance
         *       Shadow is NOT bypassed.
         *     - Eligible only for non-terminal outcomes where human review is already
         *       warranted (YELLOW/RED verdict, or FAILED/BLOCKED/ESCALATED/PENDING*).
         *     - Rate-limited per-exception (REANALYSIS_MAX_ATTEMPTS in
         *       contracts/policy.py) to prevent outcome-shopping.
         *     - Prior and new outcomes are preserved immutably in reanalysis_history
         *       and in the policy audit log (SOX).
         */
        post: operations["reanalyze_exception_api_v1_exceptions__exception_id__reanalyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Exception */
        post: operations["reject_exception_api_v1_exceptions__exception_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exceptions/{exception_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_api_v1_exceptions__exception_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Policy */
        put: operations["update_policy_api_v1_policies__tenant_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Workflow */
        post: operations["run_workflow_api_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountListResponse
         * @description GET /api/v1/accounts — list of accounts for the tenant.
         */
        AccountListResponse: {
            /** Data */
            data: components["schemas"]["AccountResponse"][];
        };
        /**
         * AccountResponse
         * @description A retail customer account within a tenant.
         */
        AccountResponse: {
            /** Bp Number */
            bp_number: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Region */
            region?: string | null;
            /** Tenant Id */
            tenant_id: string;
            /** Tier */
            tier: string;
        };
        /**
         * AdminReleaseRequest
         * @description POST /api/v1/exceptions/{id}/admin-release — admin release of RED-blocked exception.
         *
         *     Available on BLOCKED exceptions (RED verdict). Admin-only.
         *     Transitions BLOCKED → PENDING_ADMIN_REVIEW for admin to select action.
         */
        AdminReleaseRequest: {
            /** Release Reason */
            release_reason: string;
            /** Risk Acknowledgment */
            risk_acknowledgment: boolean;
        };
        /**
         * AnalysisResponse
         * @description GET /api/v1/exceptions/{id}/analysis
         */
        AnalysisResponse: {
            /** Confidence */
            confidence: number;
            /** Diagnosis */
            diagnosis: string;
            /** Lines */
            lines?: components["schemas"]["LineAnalysis"][];
            /** Resolution */
            resolution: string;
            /** Risk */
            risk: string;
        };
        /**
         * ApproveRequest
         * @description POST /api/v1/exceptions/{id}/approve — resume paused exception.
         */
        ApproveRequest: {
            /** Notes */
            notes?: string | null;
        };
        /**
         * AsyncResolveResponse
         * @description POST /api/v1/exceptions/resolve/async — queued task.
         */
        AsyncResolveResponse: {
            /**
             * Status
             * @default queued
             */
            status: string;
            /** Task Id */
            task_id: string;
        };
        /**
         * AuthTokenResponse
         * @description Auth response with JWT tokens.
         */
        AuthTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Mfa Required
             * @default false
             */
            mfa_required: boolean;
            /** Mfa Token */
            mfa_token?: string | null;
            /** Refresh Token */
            refresh_token?: string | null;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user?: components["schemas"]["UserProfile"] | null;
        };
        /**
         * ChallengeRequest
         * @description POST /api/v1/exceptions/{id}/challenge — post-execution challenge.
         *
         *     Available on RESOLVED exceptions (GREEN verdict post-execution review).
         *     Transitions RESOLVED → ESCALATED for investigation.
         */
        ChallengeRequest: {
            /** Challenge Reason */
            challenge_reason: string;
        };
        /**
         * CosignRequest
         * @description POST /api/v1/exceptions/{id}/override/cosign — second-reviewer decision
         *     on a pending high-value override (Phase 2 four-eyes control).
         *
         *     ``approve=True`` applies the pending override (lifecycle → RESOLVED);
         *     ``approve=False`` rejects it and restores the prior lifecycle. Notes
         *     are mandatory (SOX) in both cases.
         *
         *     The cosigner's identity comes from the authenticated user and must
         *     differ from the initiator — same-person cosign is a SOD violation.
         */
        CosignRequest: {
            /** Approve */
            approve: boolean;
            /** Notes */
            notes: string;
        };
        /**
         * EscalateRequest
         * @description POST /api/v1/exceptions/{id}/escalate — dedicated escalation routing.
         *
         *     Decoupled from Override: escalation changes routing (lifecycle →
         *     ESCALATED) without asserting a resolution action. ``reason`` is a
         *     mandatory SOX justification (min length 1). ``to_role`` optionally
         *     names the target role for routing metadata only — policy and state
         *     machine do not branch on it.
         */
        EscalateRequest: {
            /** Reason */
            reason: string;
            /** To Role */
            to_role?: ("admin" | "manager") | null;
        };
        /**
         * ExceptionDetailResponse
         * @description GET /api/v1/exceptions/{id} — full detail.
         */
        ExceptionDetailResponse: {
            /** Account Id */
            account_id?: string | null;
            /** Account Name */
            account_name?: string | null;
            /** Created At */
            created_at: string;
            /** Event Type */
            event_type: string;
            /** Final Status */
            final_status?: string | null;
            /** Id */
            id: string;
            /** Intent */
            intent?: string | null;
            /** Lifecycle State */
            lifecycle_state: string;
            /** Order Id */
            order_id: string;
            /** Reanalysis History */
            reanalysis_history?: {
                [key: string]: unknown;
            }[];
            /** Resolution Data */
            resolution_data?: {
                [key: string]: unknown;
            };
            /** Resolution Notes */
            resolution_notes?: string | null;
            /** Resolved Action */
            resolved_action?: string | null;
            /** Resolved By */
            resolved_by?: string | null;
            /** Selected Recipe */
            selected_recipe?: string | null;
            /** Shadow Verdict */
            shadow_verdict?: string | null;
            /** Tenant Id */
            tenant_id: string;
            /** Trace Id */
            trace_id?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /**
         * ExceptionListResponse
         * @description GET /api/v1/exceptions — paginated list.
         */
        ExceptionListResponse: {
            /** Cursor */
            cursor?: string | null;
            /** Data */
            data: components["schemas"]["ExceptionSummary"][];
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /**
         * ExceptionSummary
         * @description Single exception in a list response.
         */
        ExceptionSummary: {
            /** Account Id */
            account_id?: string | null;
            /** Account Name */
            account_name?: string | null;
            /** Created At */
            created_at: string;
            /** Event Type */
            event_type: string;
            /** Final Status */
            final_status?: string | null;
            /** Id */
            id: string;
            /** Intent */
            intent?: string | null;
            /** Lifecycle State */
            lifecycle_state: string;
            /** Order Id */
            order_id: string;
            /** Selected Recipe */
            selected_recipe?: string | null;
            /** Shadow Verdict */
            shadow_verdict?: string | null;
            /** Tenant Id */
            tenant_id: string;
            /** Updated At */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description GET /api/v1/health
         */
        HealthResponse: {
            /** Allowed Intents */
            allowed_intents: string[];
            /** Allowed Override Reason Tags */
            allowed_override_reason_tags: string[];
            /** Allowed Recipes */
            allowed_recipes: string[];
            /** Allowed Resolution Actions */
            allowed_resolution_actions: string[];
            /** Explain Mode */
            explain_mode: boolean;
            /** Kill Switch */
            kill_switch: boolean;
            /** Lifecycle States */
            lifecycle_states: string[];
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * LineAnalysis
         * @description Analysis details for a single line item.
         */
        LineAnalysis: {
            /** Diagnosis */
            diagnosis: string;
            /** Line Id */
            line_id: string;
            /** Resolution */
            resolution: string;
            /** Risk */
            risk: string;
            /** Waterfall */
            waterfall?: components["schemas"]["PricingWaterfallStep"][];
        };
        /**
         * LineItem
         * @description Single line item in an exception.
         */
        LineItem: {
            /** Description */
            description: string;
            /** Erp Price */
            erp_price: number;
            /** Line Id */
            line_id: string;
            /** Po Price */
            po_price: number;
            /** Quantity */
            quantity: number;
            /** Root Cause */
            root_cause?: string | null;
            /** Sku */
            sku: string;
            /** Uom */
            uom: string;
        };
        /**
         * LineItemsResponse
         * @description GET /api/v1/exceptions/{id}/line-items
         */
        LineItemsResponse: {
            /** Data */
            data: components["schemas"]["LineItem"][];
        };
        /**
         * LoginRequest
         * @description POST /api/auth/login — email/password auth.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MFAVerifyRequest
         * @description POST /api/auth/mfa/verify — TOTP verification.
         */
        MFAVerifyRequest: {
            /** Code */
            code: string;
            /** Mfa Token */
            mfa_token: string;
        };
        /**
         * OverrideRequest
         * @description PATCH /api/v1/exceptions/{id}/override — human override of agent recommendation.
         *
         *     Option A (Phase 1 unified action model): available on PENDING_REVIEW,
         *     ESCALATED, RESOLVED (GREEN), and BLOCKED (RED) exceptions. Analysts
         *     cannot Override — this is a manager+ action. Action must be a valid
         *     AllowedResolutionAction. Notes are mandatory (SOX).
         *
         *     The auditor identity is derived server-side from the authenticated
         *     user (user.sub) — clients must not pass a ``resolved_by`` field
         *     (identity-spoofing risk). Any such extra field is rejected (422).
         */
        OverrideRequest: {
            /** Action */
            action: string;
            /** Notes */
            notes: string;
            /**
             * Reason Tag
             * @default other
             */
            reason_tag: string;
        };
        /**
         * PolicyOverrideResponse
         * @description Response for policy update.
         */
        PolicyOverrideResponse: {
            /** Created By */
            created_by: string;
            /** Effective From */
            effective_from: string;
            /** Id */
            id: string;
            /** Policy Key */
            policy_key: string;
            /** Tenant Id */
            tenant_id: string;
            /** Value */
            value: unknown;
        };
        /**
         * PolicyUpdateRequest
         * @description PUT /api/v1/policies/{tenant_id} — update policy overrides.
         */
        PolicyUpdateRequest: {
            /** Change Reason */
            change_reason?: string | null;
            /** Policy Key */
            policy_key: string;
            /** Value */
            value: unknown;
        };
        /**
         * PricingWaterfallStep
         * @description A single step in the pricing waterfall analysis.
         */
        PricingWaterfallStep: {
            /** Detail */
            detail?: string | null;
            /** Error */
            error?: string | null;
            /** Label */
            label: string;
            /** Record */
            record?: string | null;
            /** Running */
            running?: number | null;
            /** Type */
            type: string;
            /** Value */
            value?: number | null;
        };
        /**
         * ReanalyzeRequest
         * @description POST /api/v1/exceptions/{id}/reanalyze — human-triggered graph replay.
         *
         *     Allowed only on YELLOW/RED verdicts or FAILED lifecycle. The request
         *     re-runs the full graph (including a fresh Compliance Shadow) and
         *     appends the prior and new outcome to reanalysis_history (append-only).
         *
         *     A mandatory free-text `reason` is required for SOX audit traceability.
         *     Rate-limited by REANALYSIS_MAX_ATTEMPTS (contracts/policy.py) to prevent
         *     outcome-shopping.
         */
        ReanalyzeRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * RefreshRequest
         * @description POST /api/auth/refresh — token refresh.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RejectRequest
         * @description POST /api/v1/exceptions/{id}/reject — reject paused exception.
         */
        RejectRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * ResolveRequest
         * @description POST /api/v1/exceptions/resolve — same fields as OrderEvent.
         */
        ResolveRequest: {
            /** Credit Limit */
            credit_limit?: number | null;
            /** Current Exposure */
            current_exposure?: number | null;
            /** Event Ts */
            event_ts?: string | null;
            /**
             * Event Type
             * @default EDI_850_PRICE_MISMATCH
             */
            event_type: string;
            /**
             * Line Count
             * @default 1
             */
            line_count: number;
            /**
             * Line Item
             * @default 1
             */
            line_item: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Order Id */
            order_id: string;
            /** Po Price */
            po_price: number;
            /** Requester Role */
            requester_role?: string | null;
            /** Retailer Id */
            retailer_id?: string | null;
            /** Sap Base Price */
            sap_base_price: number;
            /** Sku */
            sku?: string | null;
        };
        /**
         * ResolveResponse
         * @description Response for synchronous resolve and explain endpoints.
         */
        ResolveResponse: {
            /** Effect Results */
            effect_results?: {
                [key: string]: unknown;
            }[];
            /** Exception Id */
            exception_id: string;
            /** Execution Log */
            execution_log?: {
                [key: string]: unknown;
            } | null;
            /** Explanation */
            explanation?: string | null;
            /** Final Status */
            final_status?: string | null;
            /** Intent */
            intent?: string | null;
            /** Selected Recipe */
            selected_recipe?: string | null;
            /** Shadow Verdict */
            shadow_verdict?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * SAPActionStep
         * @description A recommended SAP action step.
         *
         *     Human-facing only — not machine-consumed. Rendered verbatim in Layer 2
         *     for operator reference. Constrained generation is NOT required here
         *     (CLAUDE.md §3).
         */
        SAPActionStep: {
            /** Description */
            description: string;
            /** Field */
            field?: string | null;
            /** Table */
            table?: string | null;
            /** Transaction */
            transaction: string;
        };
        /**
         * StatsResponse
         * @description GET /api/v1/exceptions/stats — dashboard metrics.
         */
        StatsResponse: {
            /**
             * Auto Resolved
             * @default 0
             */
            auto_resolved: number;
            /** Avg Resolution Time Seconds */
            avg_resolution_time_seconds?: number | null;
            /**
             * Blocked
             * @default 0
             */
            blocked: number;
            /** By Intent */
            by_intent?: {
                [key: string]: number;
            };
            /** By Lifecycle State */
            by_lifecycle_state?: {
                [key: string]: number;
            };
            /** By Shadow Verdict */
            by_shadow_verdict?: {
                [key: string]: number;
            };
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Manual Review
             * @default 0
             */
            manual_review: number;
            /**
             * Open Exceptions
             * @default 0
             */
            open_exceptions: number;
            /**
             * Total Exceptions
             * @default 0
             */
            total_exceptions: number;
        };
        /**
         * TraceResponse
         * @description GET /api/v1/exceptions/{id}/trace — full TraceRecord JSON.
         */
        TraceResponse: {
            /** Backend Fallback */
            backend_fallback?: string | null;
            /** Constrained Output Schemas */
            constrained_output_schemas?: {
                [key: string]: string;
            };
            /** Customer Email Draft */
            customer_email_draft?: string | null;
            /** Event Id */
            event_id: string;
            /** Explanation */
            explanation?: string | null;
            /** Final Status */
            final_status?: string | null;
            /** Gateway Calls */
            gateway_calls?: string[];
            /** Intent Selected */
            intent_selected?: string | null;
            /**
             * Is Fallback Generated
             * @default false
             */
            is_fallback_generated: boolean;
            /** Narrative */
            narrative?: string | null;
            /** Recipe Name */
            recipe_name?: string | null;
            /** Resolution Steps */
            resolution_steps?: string[];
            /** Sap Actions */
            sap_actions?: components["schemas"]["SAPActionStep"][];
            /** Shadow Policy Hits */
            shadow_policy_hits?: string[];
            /** Shadow Verdict */
            shadow_verdict?: string | null;
            /** Skill Name */
            skill_name?: string | null;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * UserProfile
         * @description GET /api/auth/me — current user profile.
         *
         *     visible_tabs and permissions are computed from roles — never stored per user.
         *     assigned_accounts drives server-side customer scope filtering.
         */
        UserProfile: {
            /** Assigned Accounts */
            assigned_accounts?: string[];
            /** Avatar Initials */
            avatar_initials?: string | null;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Org */
            org: string;
            /** Permissions */
            permissions: string[];
            /** Roles */
            roles: string[];
            /** Sub */
            sub: string;
            /** Title */
            title?: string | null;
            /** Visible Tabs */
            visible_tabs?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkflowRequest
         * @description POST /api/v1/workflows — multi-step workflow execution.
         */
        WorkflowRequest: {
            base_event: components["schemas"]["ResolveRequest"];
            /** Name */
            name: string;
            /** Steps */
            steps: components["schemas"]["WorkflowStepRequest"][];
            /** Workflow Id */
            workflow_id: string;
        };
        /** WorkflowStepRequest */
        WorkflowStepRequest: {
            /** Compensation Recipe */
            compensation_recipe?: string | null;
            /** Description */
            description: string;
            /** Input Mapping */
            input_mapping?: {
                [key: string]: string;
            };
            /** Intent */
            intent: string;
            /** Step Id */
            step_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_verify_api_auth_mfa_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MFAVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sso_callback_api_auth_sso_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sso_init_api_auth_sso_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_accounts_api_v1_accounts_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exceptions_api_v1_exceptions_get: {
        parameters: {
            query?: {
                /** @description Filter by lifecycle state */
                status?: string | null;
                /** @description Filter by intent */
                intent?: string | null;
                limit?: number;
                /** @description Pagination cursor */
                cursor?: string | null;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_api_v1_exceptions_resolve_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_async_api_v1_exceptions_resolve_async_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_explain_api_v1_exceptions_resolve_explain_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_v1_exceptions_stats_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exception_api_v1_exceptions__exception_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_release_exception_api_v1_exceptions__exception_id__admin_release_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_exceptions__exception_id__analysis_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_exception_api_v1_exceptions__exception_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    challenge_exception_api_v1_exceptions__exception_id__challenge_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_exception_api_v1_exceptions__exception_id__escalate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_line_items_api_v1_exceptions__exception_id__line_items_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineItemsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_exception_api_v1_exceptions__exception_id__override_patch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cosign_override_api_v1_exceptions__exception_id__override_cosign_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CosignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reanalyze_exception_api_v1_exceptions__exception_id__reanalyze_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReanalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_exception_api_v1_exceptions__exception_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_v1_exceptions__exception_id__trace_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    update_policy_api_v1_policies__tenant_id__put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOverrideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_workflow_api_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
