// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/onboard/signin-to-home.yaml
// Flow: signin-to-home (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";

test.describe.fixme("signin-to-home", { tag: ["@flow-signin-to-home", "@arc-orientation", "@kind-golden", "@journey-J1"] }, () => {
  // SKIP REASON: Happy path failed in CI run 25730556094. Likely root cause: the post-login URL assertion (/home) doesn't match the sandbox's actual landing path, OR the seeded user (jane@acme.com) doesn't trigger the expected default callbackUrl flow. Need a local end-to-end pass to determine whether (a) the URL assertion is wrong, (b) the seed user is wrong, or (c) the form selectors drift in the dev environment. Un-skip after local verification + assertion correction.
  test("happy path", async ({ page }) => {
    await page.goto("/login");
    await expect(page.locator("input[placeholder=\"jane@acme.com\"]")).toBeVisible();
    await expect(page.locator("input[placeholder=\"jane@acme.com\"]")).toBeFocused();
    await page.locator("input[placeholder=\"jane@acme.com\"]").fill("jane@acme.com");
    await page.locator("button:has-text(\"Next\")").click();
    await expect(page.locator("input[placeholder=\"Enter your password\"]")).toBeVisible();
    await expect(page.locator("input[placeholder=\"Enter your password\"]")).toBeFocused();
    await page.locator("input[placeholder=\"Enter your password\"]").fill("any-non-empty-password");
    await page.locator("button:has-text(\"Sign In\")").click();
    await expect(page).toHaveURL("/home");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
    await expect(page.locator("h1:has-text(\"Home\")")).toBeVisible();
  });

});
