// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/onboard/signin-to-home.yaml
// Flow: signin-to-home (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";

test.describe.fixme("signin-to-home", () => {
  // SKIP REASON: Sign-in flow's assertions on the post-login landing page need live-backend validation. asoe2 sandbox seed + role-based home-page routing changed under Issue #133 (/inbox retired, /home introduced); the focus + chrome assertions assume the pre-#133 destination. Un-skip after the local end-to-end pass.
  test("happy path", async ({ page }) => {
    await page.goto("/login");
    await expect(page.locator("input[placeholder=\"jane@acme.com\"]")).toBeVisible();
    await expect(page.locator("input[placeholder=\"jane@acme.com\"]")).toBeFocused();
    await page.locator("input[placeholder=\"jane@acme.com\"]").fill("jane@acme.com");
    await page.locator("button:has-text(\"Next\")").click();
    await expect(page.locator("input[placeholder=\"Enter your password\"]")).toBeVisible();
    await expect(page.locator("input[placeholder=\"Enter your password\"]")).toBeFocused();
    await page.locator("input[placeholder=\"Enter your password\"]").fill("any-non-empty-password");
    await page.locator("button:has-text(\"Sign In\")").click();
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"status-announcer\"]")).toBeVisible();
  });

});
