// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/recover/back-from-misroute.yaml
// Flow: back-from-misroute (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";

test.describe("back-from-misroute", () => {
  test("happy path", async ({ page }) => {
    await page.goto("/inbox");
    await expect(page.locator("nav")).toBeVisible();
    await expect(page.locator("[data-testid=\"inbox-row\"]")).toBeVisible();
    await page.locator("[role=\"button\"][aria-label*=\"Where is my shipment\"]").click();
    await expect(page).toHaveURL("/inbox");
    await expect(page.locator("text=\"Where is my shipment? SO 4500019882\"")).toBeVisible();
    await page.locator("[role=\"button\"][aria-label*=\"Beverages Dept\"]").click();
    await expect(page).toHaveURL("/inbox");
  });

});
