// AUTO-GENERATED by e2e/flow-codegen.ts. DO NOT EDIT.
// Source: e2e/flows/recover/back-from-misroute.yaml
// Flow: back-from-misroute (golden)
// Edits are clobbered by `bun run flows:gen`. Update the YAML.

import { expect, test } from "@playwright/test";
import { loginAs, USERS } from "../../../tests/browser/_helpers";

test.describe("back-from-misroute", { tag: ["@flow-back-from-misroute", "@arc-orientation", "@kind-golden", "@journey-J3"] }, () => {
  test("happy path", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.goto("/cases?source=manual_order");
    await expect(page.locator("button[aria-label^=\"Open case \"]")).toBeVisible();
    await page.locator("button[aria-label^=\"Open case \"] >> nth=0").click();
    await expect(page).toHaveURL(new RegExp("^/cases/[^/?#]+$"));
    await expect(page.locator("[aria-label=\"Back to cases list\"]")).toBeVisible();
    await page.locator("[aria-label=\"Back to cases list\"]").click();
    await expect(page).toHaveURL("/cases");
  });

  test("state: empty", async ({ page }) => {
    await loginAs(page, USERS.MANAGER);
    await page.route("/api/v1/cases**", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: "{\"items\":[],\"total\":0,\"cursor\":null,\"has_more\":false}",
      });
    });
    await page.goto("/cases?source=manual_order");
    await expect(page.getByText("No cases match the current filters.")).toBeVisible();
  });

});
