// AUTO-GENERATED — do not edit by hand.
// Source: tests/contract/snapshots/scenario_catalog.yaml
//          (synced from ../asoe2/fixtures/scenarios/catalog.yaml)
// Regenerate with: npm run gen:mock-data
//
// PARALLEL artifact (Guardrail #2): NOT yet consumed by the app. The
// hand-authored src/lib/mock-data/exceptions.ts remains the source the
// API client uses until the catalog reaches MOCK_ORDER_ANALYSES parity.
// `created_at`/`updated_at` are synthetic sentinels (the catalog carries
// no per-record audit timestamps; the real backend stamps those).

import type { ExceptionSummary } from "@/types/exceptions";

export const CATALOG_EXCEPTIONS: ExceptionSummary[] = [
  {
    "id": "exc-001",
    "tenant_id": "acme-corp",
    "order_id": "SO-WMT-1001",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "CONTRACTUAL_CORRECTION",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-001",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc."
  },
  {
    "id": "exc-003",
    "tenant_id": "acme-corp",
    "order_id": "SO-TGT-2200",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "CREDIT_BLOCK",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-003",
    "shadow_verdict": "RED",
    "account_id": "acct-R-13",
    "account_name": "Target Corp."
  },
  {
    "id": "exc-026",
    "tenant_id": "acme-corp",
    "order_id": "EML-PO-2026-0042",
    "event_type": "EMAIL_ORDER_ENTRY_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-04-30T10:12:00Z",
    "updated_at": "2026-04-30T10:12:00Z",
    "parent_case_id": "case-for-exc-026",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors"
  },
  {
    "id": "exc-027",
    "tenant_id": "acme-corp",
    "order_id": "PO-WMT-Q1-RESET-001",
    "event_type": "EDI_850_PRICE_HOLD",
    "intent": "PRICE_HOLD_RELEASE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-027",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc."
  },
  {
    "id": "exc-028",
    "tenant_id": "acme-corp",
    "order_id": "PO-WMT-Q1-RESET-001",
    "event_type": "BACK_ORDER_OOS",
    "intent": "BACK_ORDER",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-028",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc."
  },
  {
    "id": "exc-029",
    "tenant_id": "acme-corp",
    "order_id": "PO-WMT-Q1-RESET-001-R2",
    "event_type": "EDI_850_DUPLICATE_PO",
    "intent": "DUPLICATE_PO",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-029",
    "shadow_verdict": "RED",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc."
  },
  {
    "id": "exc-030",
    "tenant_id": "acme-corp",
    "order_id": "PO-COST-EOQ-2026Q1",
    "event_type": "OVER_MAX_QTY",
    "intent": "OVER_MAX",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-030",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale"
  },
  {
    "id": "exc-031",
    "tenant_id": "acme-corp",
    "order_id": "PO-COST-EOQ-2026Q1",
    "event_type": "PALLET_CONFIG_VIOLATION",
    "intent": "PALLET_CONFIG",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-031",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale"
  },
  {
    "id": "exc-032",
    "tenant_id": "acme-corp",
    "order_id": "PO-KR-WK15-2026",
    "event_type": "MIN_ORDER_QTY",
    "intent": "MIN_ORDER_QTY",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-032",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co."
  },
  {
    "id": "exc-033",
    "tenant_id": "acme-corp",
    "order_id": "PO-KR-WK15-2026",
    "event_type": "DELIVERY_DELAY",
    "intent": "DELIVERY_DELAY",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-033",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co."
  },
  {
    "id": "exc-040",
    "tenant_id": "acme-corp",
    "order_id": "PO-SED-2026-0418",
    "event_type": "EMAIL_ORDER_CHANGE_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-18T09:02:00Z",
    "updated_at": "2026-05-18T09:02:00Z",
    "parent_case_id": "case-for-exc-040",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors"
  },
  {
    "id": "exc-041",
    "tenant_id": "acme-corp",
    "order_id": "PO-SED-2026-0502",
    "event_type": "EMAIL_ORDER_CHANGE_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-18T11:20:00Z",
    "updated_at": "2026-05-18T11:20:00Z",
    "parent_case_id": "case-for-exc-041",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors"
  },
  {
    "id": "exc-042",
    "tenant_id": "acme-corp",
    "order_id": "PO-WMT-2026-1101",
    "event_type": "EMAIL_ORDER_CHANGE_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "ESCALATED",
    "created_at": "2026-05-19T08:15:00Z",
    "updated_at": "2026-05-19T08:15:00Z",
    "parent_case_id": "case-for-exc-042",
    "shadow_verdict": "RED",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc."
  },
  {
    "id": "exc-043",
    "tenant_id": "acme-corp",
    "order_id": "PO-KR-2026-0907",
    "event_type": "EMAIL_ORDER_CHANGE_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-19T13:40:00Z",
    "updated_at": "2026-05-19T13:40:00Z",
    "parent_case_id": "case-for-exc-043",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co."
  },
  {
    "id": "exc-044",
    "tenant_id": "acme-corp",
    "order_id": "EML-INQ-2026-0061",
    "event_type": "EMAIL_INQUIRY",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-044",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors"
  },
  {
    "id": "exc-045",
    "tenant_id": "acme-corp",
    "order_id": "EML-CMP-2026-0062",
    "event_type": "EMAIL_COMPLAINT",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "ESCALATED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-045",
    "shadow_verdict": "RED",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc."
  },
  {
    "id": "exc-046",
    "tenant_id": "acme-corp",
    "order_id": "EDI-PO-2026-7781",
    "event_type": "EMAIL_ORDER_ENTRY_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-05-22T07:10:00Z",
    "updated_at": "2026-05-22T07:10:00Z",
    "parent_case_id": "case-for-exc-046",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co."
  },
  {
    "id": "exc-047",
    "tenant_id": "acme-corp",
    "order_id": "EML-GEN-2026-0071",
    "event_type": "EMAIL_GENERAL",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-047",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors"
  },
  {
    "id": "exc-dup-crosschannel",
    "tenant_id": "acme-corp",
    "order_id": "PO-88421",
    "event_type": "EMAIL_ORDER_ENTRY_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-04-12T09:30:00Z",
    "updated_at": "2026-04-12T09:30:00Z",
    "parent_case_id": "case-for-exc-dup-crosschannel",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co."
  },
  {
    "id": "exc-dup-resend",
    "tenant_id": "acme-corp",
    "order_id": "EML-PO-2026-0042",
    "event_type": "EMAIL_ORDER_ENTRY_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-01T08:45:00Z",
    "updated_at": "2026-05-01T08:45:00Z",
    "parent_case_id": "case-for-exc-dup-resend",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors"
  },
  {
    "id": "exc-messy",
    "tenant_id": "acme-corp",
    "order_id": "exc-messy",
    "event_type": "EMAIL_ORDER_ENTRY_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-23T16:42:00Z",
    "updated_at": "2026-05-23T16:42:00Z",
    "parent_case_id": "case-for-exc-messy",
    "shadow_verdict": "YELLOW",
    "account_name": "Sunrise Beverage"
  }
];

export const CATALOG_EXCEPTION_COUNT = 21 as const;
