// AUTO-GENERATED — do not edit by hand.
// Source: tests/contract/snapshots/scenario_catalog.yaml
//          (synced from ../asoe2/fixtures/scenarios/catalog.yaml)
// Regenerate with: npm run gen:mock-data
//
// PARALLEL artifact (Guardrail #2): NOT yet consumed by the app. The
// hand-authored src/lib/mock-data/exceptions.ts remains the source the
// API client uses until the catalog reaches MOCK_ORDER_ANALYSES parity.
// `created_at`/`updated_at` are synthetic sentinels (the catalog carries
// no per-record audit timestamps; the real backend stamps those).

import type { ExceptionSummary } from "@/types/exceptions";

export const CATALOG_EXCEPTIONS: ExceptionSummary[] = [
  {
    "id": "exc-001",
    "tenant_id": "acme-corp",
    "order_id": "PO-001-R-11",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "CONTRACTUAL_CORRECTION",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-001",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "PriceAdjustmentRecipe.py"
  },
  {
    "id": "exc-002",
    "tenant_id": "acme-corp",
    "order_id": "PO-002-R-12",
    "event_type": "EDI_850_DUPLICATE_PO",
    "intent": "DUPLICATE_PO",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-002",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "DuplicatePORecipe.py"
  },
  {
    "id": "exc-003",
    "tenant_id": "acme-corp",
    "order_id": "PO-003-R-13",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "CREDIT_BLOCK",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-003",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-13",
    "account_name": "Target Corp.",
    "selected_recipe": "CreditHoldReleaseRecipe.py"
  },
  {
    "id": "exc-004",
    "tenant_id": "acme-corp",
    "order_id": "PO-004-R-14",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "MASS_PRICING_ERROR",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-004",
    "shadow_verdict": "RED",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale"
  },
  {
    "id": "exc-005",
    "tenant_id": "acme-corp",
    "order_id": "PO-005-R-11",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "CONTRACTUAL_CORRECTION",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-005",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "PriceAdjustmentRecipe.py"
  },
  {
    "id": "exc-006",
    "tenant_id": "acme-corp",
    "order_id": "PO-006-R-12",
    "event_type": "EDI_850_DUPLICATE_PO",
    "intent": "DUPLICATE_PO",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-006",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "DuplicatePORecipe.py"
  },
  {
    "id": "exc-007",
    "tenant_id": "acme-corp",
    "order_id": "PO-007-R-13",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "CREDIT_BLOCK",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-007",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-13",
    "account_name": "Target Corp.",
    "selected_recipe": "CreditHoldReleaseRecipe.py"
  },
  {
    "id": "exc-008",
    "tenant_id": "acme-corp",
    "order_id": "PO-008-R-14",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "CONTRACTUAL_CORRECTION",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-008",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale",
    "selected_recipe": "PriceAdjustmentRecipe.py"
  },
  {
    "id": "exc-009",
    "tenant_id": "acme-corp",
    "order_id": "PO-009-R-11",
    "event_type": "EDI_850_DUPLICATE_PO",
    "intent": "DUPLICATE_PO",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-009",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "DuplicatePORecipe.py"
  },
  {
    "id": "exc-010",
    "tenant_id": "acme-corp",
    "order_id": "PO-010-R-12",
    "event_type": "BACK_ORDER_OOS",
    "intent": "BACK_ORDER",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-010",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "BackOrderResolutionRecipe.py"
  },
  {
    "id": "exc-011",
    "tenant_id": "acme-corp",
    "order_id": "PO-011-R-13",
    "event_type": "BACK_ORDER_OOS",
    "intent": "BACK_ORDER",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-011",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-13",
    "account_name": "Target Corp.",
    "selected_recipe": "BackOrderResolutionRecipe.py"
  },
  {
    "id": "exc-012",
    "tenant_id": "acme-corp",
    "order_id": "PO-012-R-14",
    "event_type": "OVER_MAX_QTY",
    "intent": "OVER_MAX",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-012",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale",
    "selected_recipe": "OverMaxTrimRecipe.py"
  },
  {
    "id": "exc-013",
    "tenant_id": "acme-corp",
    "order_id": "PO-013-R-11",
    "event_type": "MIN_ORDER_QTY",
    "intent": "MIN_ORDER_QTY",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-013",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "MOQRoundUpRecipe.py"
  },
  {
    "id": "exc-014",
    "tenant_id": "acme-corp",
    "order_id": "PO-014-R-12",
    "event_type": "PALLET_CONFIG_VIOLATION",
    "intent": "PALLET_CONFIG",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-014",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "PalletAlignmentRecipe.py"
  },
  {
    "id": "exc-015",
    "tenant_id": "acme-corp",
    "order_id": "PO-015-R-11",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "CONTRACTUAL_CORRECTION",
    "lifecycle_state": "FAILED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-015",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "PriceAdjustmentRecipe.py"
  },
  {
    "id": "exc-016",
    "tenant_id": "acme-corp",
    "order_id": "PO-016-R-13",
    "event_type": "DELIVERY_DELAY",
    "intent": "DELIVERY_DELAY",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-016",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-13",
    "account_name": "Target Corp.",
    "selected_recipe": "DeliveryDelayResolutionRecipe.py"
  },
  {
    "id": "exc-017",
    "tenant_id": "acme-corp",
    "order_id": "PO-017-R-11",
    "event_type": "EDI_850_PRICE_HOLD",
    "intent": "PRICE_HOLD_RELEASE",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-017",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "PriceHoldReleaseRecipe.py"
  },
  {
    "id": "exc-018",
    "tenant_id": "acme-corp",
    "order_id": "PO-018-R-12",
    "event_type": "EDI_850_PRICE_HOLD",
    "intent": "PRICE_HOLD_RELEASE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-018",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "PriceHoldReleaseRecipe.py"
  },
  {
    "id": "exc-019",
    "tenant_id": "acme-corp",
    "order_id": "PO-019-R-13",
    "event_type": "EDI_850_LINE_MISMATCH",
    "intent": "EDI_MISMATCH",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-019",
    "shadow_verdict": "RED",
    "account_id": "acct-R-13",
    "account_name": "Target Corp.",
    "selected_recipe": "EdiMismatchRecipe.py"
  },
  {
    "id": "exc-020",
    "tenant_id": "acme-corp",
    "order_id": "PO-020-R-14",
    "event_type": "EDI_850_LINE_MISMATCH",
    "intent": "EDI_MISMATCH",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-020",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale",
    "selected_recipe": "EdiMismatchRecipe.py"
  },
  {
    "id": "exc-021",
    "tenant_id": "acme-corp",
    "order_id": "PO-021-R-11",
    "event_type": "EDI_850_LINE_MISMATCH",
    "intent": "CONTRACTUAL_CORRECTION",
    "lifecycle_state": "RESOLVED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-021",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "PriceAdjustmentRecipe.py"
  },
  {
    "id": "exc-022",
    "tenant_id": "acme-corp",
    "order_id": "PO-022-R-11",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "MASS_PRICING_ERROR",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-022",
    "shadow_verdict": "RED",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc."
  },
  {
    "id": "exc-023",
    "tenant_id": "acme-corp",
    "order_id": "PO-023-R-12",
    "event_type": "EDI_850_PRICE_MISMATCH",
    "intent": "MASS_PRICING_ERROR",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-023",
    "shadow_verdict": "RED",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co."
  },
  {
    "id": "exc-024",
    "tenant_id": "acme-corp",
    "order_id": "PO-024-R-13",
    "event_type": "EDI_850_DUPLICATE_PO",
    "intent": "DUPLICATE_PO",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-024",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-13",
    "account_name": "Target Corp.",
    "selected_recipe": "DuplicatePORecipe.py"
  },
  {
    "id": "exc-025",
    "tenant_id": "acme-corp",
    "order_id": "PO-025-R-14",
    "event_type": "EDI_850_PRICE_HOLD",
    "intent": "PRICE_HOLD_RELEASE",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-025",
    "shadow_verdict": "RED",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale",
    "selected_recipe": "PriceHoldReleaseRecipe.py"
  },
  {
    "id": "exc-026",
    "tenant_id": "acme-corp",
    "order_id": "EML-PO-2026-0042",
    "event_type": "EMAIL_ORDER_ENTRY_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-04-30T10:12:00Z",
    "updated_at": "2026-04-30T10:12:00Z",
    "parent_case_id": "case-for-exc-026",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  },
  {
    "id": "exc-027",
    "tenant_id": "acme-corp",
    "order_id": "PO-WMT-Q1-RESET-001",
    "event_type": "EDI_850_PRICE_HOLD",
    "intent": "PRICE_HOLD_RELEASE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-PO-WMT-Q1-RESET-001",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "PriceHoldReleaseRecipe.py"
  },
  {
    "id": "exc-028",
    "tenant_id": "acme-corp",
    "order_id": "PO-WMT-Q1-RESET-001",
    "event_type": "BACK_ORDER_OOS",
    "intent": "BACK_ORDER",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-PO-WMT-Q1-RESET-001",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "BackOrderResolutionRecipe.py"
  },
  {
    "id": "exc-029",
    "tenant_id": "acme-corp",
    "order_id": "PO-WMT-Q1-RESET-001",
    "event_type": "EDI_850_DUPLICATE_PO",
    "intent": "DUPLICATE_PO",
    "lifecycle_state": "BLOCKED",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-PO-WMT-Q1-RESET-001",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "DuplicatePORecipe.py"
  },
  {
    "id": "exc-030",
    "tenant_id": "acme-corp",
    "order_id": "PO-030-R-14",
    "event_type": "OVER_MAX_QTY",
    "intent": "OVER_MAX",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-030",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale",
    "selected_recipe": "OverMaxTrimRecipe.py"
  },
  {
    "id": "exc-031",
    "tenant_id": "acme-corp",
    "order_id": "PO-031-R-14",
    "event_type": "PALLET_CONFIG_VIOLATION",
    "intent": "PALLET_CONFIG",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-031",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-14",
    "account_name": "Costco Wholesale",
    "selected_recipe": "PalletAlignmentRecipe.py"
  },
  {
    "id": "exc-032",
    "tenant_id": "acme-corp",
    "order_id": "PO-032-R-12",
    "event_type": "MIN_ORDER_QTY",
    "intent": "MIN_ORDER_QTY",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-032",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "MOQRoundUpRecipe.py"
  },
  {
    "id": "exc-033",
    "tenant_id": "acme-corp",
    "order_id": "PO-033-R-12",
    "event_type": "DELIVERY_DELAY",
    "intent": "DELIVERY_DELAY",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-033",
    "shadow_verdict": "YELLOW",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "DeliveryDelayResolutionRecipe.py"
  },
  {
    "id": "exc-040",
    "tenant_id": "acme-corp",
    "order_id": "PO-SED-2026-0418",
    "event_type": "EMAIL_ORDER_CHANGE_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-18T09:02:00Z",
    "updated_at": "2026-05-18T09:02:00Z",
    "parent_case_id": "case-for-exc-040",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  },
  {
    "id": "exc-041",
    "tenant_id": "acme-corp",
    "order_id": "PO-SED-2026-0502",
    "event_type": "EMAIL_ORDER_CHANGE_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-18T11:20:00Z",
    "updated_at": "2026-05-18T11:20:00Z",
    "parent_case_id": "case-for-exc-041",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  },
  {
    "id": "exc-042",
    "tenant_id": "acme-corp",
    "order_id": "PO-WMT-2026-1101",
    "event_type": "EMAIL_ORDER_CHANGE_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-19T08:15:00Z",
    "updated_at": "2026-05-19T08:15:00Z",
    "parent_case_id": "case-for-exc-042",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  },
  {
    "id": "exc-043",
    "tenant_id": "acme-corp",
    "order_id": "PO-KR-2026-0907",
    "event_type": "EMAIL_ORDER_CHANGE_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-19T13:40:00Z",
    "updated_at": "2026-05-19T13:40:00Z",
    "parent_case_id": "case-for-exc-043",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  },
  {
    "id": "exc-044",
    "tenant_id": "acme-corp",
    "order_id": "EML-INQ-2026-0061",
    "event_type": "EMAIL_INQUIRY",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-044",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  },
  {
    "id": "exc-045",
    "tenant_id": "acme-corp",
    "order_id": "EML-CMP-2026-0062",
    "event_type": "EMAIL_COMPLAINT",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-045",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-11",
    "account_name": "Walmart Inc.",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  },
  {
    "id": "exc-046",
    "tenant_id": "acme-corp",
    "order_id": "EDI-PO-2026-7781",
    "event_type": "EMAIL_ORDER_ENTRY_REQUEST",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-05-22T07:10:00Z",
    "updated_at": "2026-05-22T07:10:00Z",
    "parent_case_id": "case-for-exc-046",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-12",
    "account_name": "Kroger Co.",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  },
  {
    "id": "exc-047",
    "tenant_id": "acme-corp",
    "order_id": "EML-GEN-2026-0071",
    "event_type": "EMAIL_GENERAL",
    "intent": "MANUAL_ORDER_INTAKE",
    "lifecycle_state": "PENDING_REVIEW",
    "created_at": "2026-06-13T00:00:00Z",
    "updated_at": "2026-06-13T00:00:00Z",
    "parent_case_id": "case-for-exc-047",
    "shadow_verdict": "GREEN",
    "account_id": "acct-R-15",
    "account_name": "Southeast Beverage Distributors",
    "selected_recipe": "EmailOrderEntryRecipe.py"
  }
];

export const CATALOG_EXCEPTION_COUNT = 41 as const;
